### ISSUE TITLE
UK / IND Leads research IT

### ISSUE THREAD

**Issue by sdsouza33** [sdsouza33/B2BDYNAMICS#4]

**Comment by sdsouza33** [comment]
Need to send questions and connect with Indian and UK based IT companies. The questions will help in forming the copy for the IT company

**Comment by isedwards** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
akash9182, @magrossm, @tuluigi, @FantasticMrFaris, @vkx, @jeganad, @kendling, @Chehps, @liazheyua, @ysn47, @HAL-XP, @nono16t, @dajneem23, @payam-alexander, @czechowskim, @SorenSaket, @dompap123, @futurist, @landon-m, @fidke, @NguyenAnh11, @zzeric, @qitianchan, @arturfie, @Theophile91, @argaghulamahmad, @CJ99, @lanshango820, @yagerfgcs, @SonnyRR, @Anna1-1, @oatmeal3000, @pablo-pereira, @sol-wasserman, @AGDholo, @hsut, @wangzou1995, @trevoursithole, @zakaruhma, @wangzhiqing123, @DamilolaAdegunwa, @fjcamillo, @misszero, @fowfofnsnsaofi, @cyberbandit0, @poch3ng, @Sudh-S, @girishso, @Bigg-Iron, @PhyzexD
